trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: TerraformCLI@0
  displayName: 'Terraform Init'
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure'
    backendType: 'azurerm'
    backendServiceArm: 'azure-service-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'backend-rg'
    backendAzureRmResourceGroupLocation: 'eastus'
    backendAzureRmStorageAccountName: 'storageacctnamexm1'
    backendAzureRmContainerName: 'storageaccntcon'
    backendAzureRmKey: 'k8.tfstate'


- task: TerraformCLI@0
  displayName: 'Terraform Validate'
  inputs:   
    command: 'validate'
    allowTelemetryCollection: true


- task: TerraformCLI@0
  displayName: 'Terraform plan'
  inputs:
    command: 'plan'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: 'Terraform apply'
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure'
    environmentServiceName: 'azure-service-connection'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
